### ISSUE TITLE
Does not support PHP 8.0, 8.1, 8.2, 8.3

### ISSUE THREAD

**Issue by vukanac** [structurizr-php/structurizr-php#231]
When trying on PHP 8.2.12:
`composer require structurizr-php/structurizr-php`
gives me an error:

    Package structurizr-php/structurizr-php has requirements incompatible with your PHP version,
    PHP extensions and Composer version:
    - structurizr-php/structurizr-php 0.3.0 requires php ^7.3 which does not match your installed version 8.2.12.

**Comment by tolik518** [comment]
It looks like the library was actually updated to work with php 8 in this [commit](https://github.com/structurizr-php/structurizr-php/commit/f6d855d9541824ddf0dd9dbcd16fee34246f0b20) but the maintainers didn't issue a new release. 

So the solution would be either using the master branch or @norberttech / @akondas will make a new release, since the feature is ready and it basically only needs a new tag

**Comment by akondas** [comment]
Done: https://github.com/structurizr-php/structurizr-php/releases/tag/0.4.0

**Comment by tolik518** [comment]
Perfect, thanks for the fast reaction @akondas
