### ISSUE TITLE
Key/description order in constructor for views are different per view

### ISSUE THREAD

**Issue by alleknalle** [structurizr-php/structurizr-php#71]
@norberttech in different views the $key and $description order is different in the constructor. I would suggest to make this the same order for all of them. What is your opinion about this? If we would make the order the same for all views I suggest to make it $key, $description. This is then a 'breaking' change since it would affect the current way views are created.

**Comment by norberttech** [comment]
well technically speaking this lib didn't have yet a stable release, so BC breaks should be fine but on the other hand, I would like to avoid breaking BC just to reorganize the order of parameters :| 
@akondas any thoughts?

**Comment by akondas** [comment]
I would allow such a change, my motivation:
1. No stable release so we can make such changes
2. This library is used to draw diagrams, so it's not something that will break your production code (unless you sell these diagrams for money ... :thinking:)
3. We will add the relevant info in the changelog - so it shouldn't be a problem.
4. I have checked my diagrams and there is no conflict with me.

Actually how many places where this order does not match? Because if it's one or two classes it's cool, with more, you can still think about it.

**Comment by alleknalle** [comment]
It looks like the order only doesn't match in DynamicView in a couple of places. But like stated, I would suggest to change the order from $description, $key, to $key, $description on all Views, since that order is more logical (and used in all the createView methods in ViewSet and in the DSL format as well).
I think most users use the createView methods from ViewSet, which won't change, since the order is correct there (in my opinion) :-)

**Comment by norberttech** [comment]
Could you please check how it looks in Java lib which we are porting here? Order is unified there?

**Comment by alleknalle** [comment]
@norberttech it's $key, $description there as well

![image](https://user-images.githubusercontent.com/5603434/113831855-5574da80-9788-11eb-9f5c-a88936923106.png)

**Comment by norberttech** [comment]
yeah, so lets change this, all points made by @akondas makes sense and you are right that it should be unified

**Comment by alleknalle** [comment]
Done in PR https://github.com/structurizr-php/structurizr-php/pull/75

**Comment by norberttech** [comment]
merged 🎉
